// Configuración de imágenes
const IMAGE_CONFIG = {
  "products": {
    "New appetizer plate": "images/products/110.jpg",
    "Large jam jar": "images/products/002.jpg",
    "Small serving boat": "images/products/003.jpg",
    "Large serving boat": "images/products/004.jpg",
    "Wine mug": "images/products/005.jpg",
    "Biscuit bowl": "images/products/006.jpg",
    "Jug 0.25 L": "images/products/007.jpg",
    "Jug 0.50 L": "images/products/008.jpg",
    "Jug 1.00 L": "images/products/009.jpg",
    "Jug 1.50 L": "images/products/010.jpg",
    "Jug 2.00 L": "images/products/011.jpg",
    "Coffee pot x 6": "images/products/016.jpg",
    "Coffee pot x 12": "images/products/017.jpg",
    "Candlestick with handle": "images/products/018.jpg",
    "New candlestick": "images/products/019.jpg",
    "Bowl - 15 cm": "images/products/020.jpg",
    "Bowl - 17 cm": "images/products/021.jpg",
    "Central appetizer bowl": "images/products/022.jpg",
    "Side appetizer bowl": "images/products/023.jpg",
    "Side ice cream bowl": "images/products/024.jpg",
    "Small fruit bowl": "images/products/025.jpg",
    "Medium fruit bowl": "images/products/026.jpg",
    "Large fruit bowl": "images/products/027.jpg",
    "Crudités bowl": "images/products/028.jpg",
    "Small oval-shaped bowl": "images/products/029.jpg",
    "Medium oval-shaped bowl": "images/products/030.jpg",
    "Large oval-shaped bowl": "images/products/031.jpg",
    "Small rectangular-shaped bowl": "images/products/032.jpg",
    "Medium rectangular-shaped bowl": "images/products/033.jpg",
    "Large rectangular-shaped bowl": "images/products/034.jpg",
    "Small spaghetti bowl": "images/products/035.jpg",
    "Large spaghetti bowl": "images/products/036.jpg",
    "Spoon": "images/products/037.jpg",
    "Small hexagonal plate": "images/products/038.jpg",
    "Large hexagonal plate": "images/products/039.jpg",
    "Cheese bowl with cover": "images/products/040.jpg",
    "Cheese bowl": "images/products/041.jpg",
    "Strawberry bowl": "images/products/042.jpg",
    "New fruit bowl with handles": "images/products/109.jpg",
    "Shallow fruit bowl with feet": "images/products/044.jpg",
    "High fruit bowl - 30 cm diameter": "images/products/045.jpg",
    "High salad bowl, diameter 33 cm": "images/products/046.jpg",
    "Oval salad bowl": "images/products/047.jpg",
    "Milk jug - 10 cm": "images/products/048.jpg",
    "Milk jug - 12 cm": "images/products/049.jpg",
    "Milk jug - 16 cm": "images/products/050.jpg",
    "Milk jug - 18 cm": "images/products/051.jpg",
    "Half-moon plate": "images/products/052.jpg",
    "Oval dish 16x22": "images/products/053.jpg",
    "Oval dish 28x21": "images/products/054.jpg",
    "Oval dish 32x24": "images/products/055.jpg",
    "Oval dish 38x30": "images/products/056.jpg",
    "Oval dish 45x36": "images/products/057.jpg",
    "Small oval fish dish": "images/products/058.jpg",
    "Large oval fish dish": "images/products/059.jpg",
    "Saucer for small coffee cup": "images/products/060.jpg",
    "Saucer for tea cup": "images/products/061.jpg",
    "Saucer for large coffee cup": "images/products/062.jpg",
    "Smooth saucer for large cup with\nhandle": "images/products/063.jpg",
    "Regular saucer for large cup\nwithout handle": "images/products/064.jpg",
    "Saucer for English tea cup Ø 15 cm": "images/products/049.jpg",
    "Plate - 15 cm": "images/products/066.jpg",
    "Plate - 19 cm": "images/products/067.jpg",
    "Plate - 22 cm": "images/products/068.jpg",
    "Flat plate - 25 cm": "images/products/069.jpg",
    "Deep plate - 25 cm": "images/products/070.jpg",
    "Deep serving dish - 28 cm": "images/products/071.jpg",
    "Deep appetizer plate": "images/products/072.jpg",
    "Stew dish with lid": "images/products/073.jpg",
    "Oil and vinegar set": "images/products/074.jpg",
    "Face powder dish": "images/products/075.jpg",
    "Jewellery box": "images/products/076.jpg",
    "Comb holder": "images/products/077.jpg",
    "Soap dish": "images/products/078.jpg",
    "Bread stick holder": "images/products/079.jpg",
    "Spoon holder": "images/products/108.jpg",
    "Tooth pick holder": "images/products/080.jpg",
    "Egg cup": "images/products/081.jpg",
    "Salt pot": "images/products/082.jpg",
    "Sauce boat": "images/products/083.jpg",
    "Lemon squeezer": "images/products/111.jpg",
    "Small coffee cup": "images/products/084.jpg",
    "Tea cup": "images/products/085.jpg",
    "Large coffee cup": "images/products/086.jpg",
    "Large smooth cup with handle": "images/products/087.jpg",
    "Large regular cup without handle": "images/products/088.jpg",
    "English tea cup": "images/products/089.jpg",
    "Small soup bowl": "images/products/090.jpg",
    "Large soup bowl": "images/products/091.jpg",
    "Teapot x 6 - 12 cm": "images/products/092.jpg",
    "Teapot x 12 - 14 cm": "images/products/093.jpg",
    "Round plate - 28 cm": "images/products/094.jpg",
    "Round plate - 32 cm": "images/products/095.jpg",
    "Round plate - 40 cm": "images/products/096.jpg",
    "Small tray": "images/products/097.jpg",
    "Large tray": "images/products/098.jpg",
    "Rectangular tray with small\nhandles": "images/products/099.jpg",
    "Museum tray": "images/products/107.jpg",
    "Sugar bowl - 8 cm": "images/products/101.jpg",
    "Sugar bowl - 9 cm": "images/products/102.jpg",
    "Sugar bowl - 11 cm": "images/products/103.jpg",
    "Soup serving bowl x 2": "images/products/104.jpg",
    "Soup serving bowl x 6": "images/products/105.jpg",
    "Soup serving bowl x 12": "images/products/106.jpg"
  },
  "comodines": {
    "GIALLO FIORE": "images/comodines/GIALLO_FIORE.png",
    "BIANCO FIORE": "images/comodines/BIANCO_FIORE.png",
    "MAZZETTO": "images/comodines/MAZZETTO.png",
    "GAROFANO BLU": "images/comodines/GAROFANO_BLU.png",
    "GAROFANO IMOLA": "images/comodines/GAROFANO_IMOLA.png",
    "GAROFANO LAVI": "images/comodines/GAROFANO_LAVI.png",
    "GAROFANO TIFFANY": "images/comodines/GAROFANO_TIFFANY.png",
    "GAROFANO ROSA": "images/comodines/GAROFANO_ROSA.png",
    "ROSSO E ORO": "images/comodines/ROSSO_E_ORO.png",
    "AVORIO E ORO": "images/comodines/AVORIO_E_ORO.png"
  }
};
